# Generated by Django 4.2.19 on 2025-03-18 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng'), ('maintenance', 'Bảo trì'), ('occupied', 'Đang sử dụng')], default='available', max_length=20)),
                ('max_hours_per_day', models.FloatField()),
                ('operating_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('productivity', models.FloatField()),
                ('salary', models.FloatField()),
                ('overtime_cost', models.FloatField()),
                ('shifts', models.ManyToManyField(related_name='workers', to='scheduling.shift')),
                ('skills', models.ManyToManyField(related_name='workers', to='scheduling.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, 'Thấp'), (2, 'Trung bình'), (3, 'Cao'), (4, 'Rất cao'), (5, 'Khẩn cấp')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('required_machine_type', models.CharField(max_length=255)),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.job')),
                ('required_skills', models.ManyToManyField(related_name='jobs', to='scheduling.skill')),
            ],
        ),
    ]
