# Generated by Django 4.2.19 on 2025-03-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('max_hours_per_day', models.FloatField()),
                ('operating_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('productivity', models.FloatField()),
                ('available_shifts', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('overtime_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('required_skills', models.CharField(max_length=255)),
                ('required_machine_type', models.CharField(max_length=255)),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.job')),
            ],
        ),
    ]
